language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - cd $TRAVIS_BUILD_DIR/udagram-api-feed
  - docker build -t udagram-api-feed .
  - docker tag udagram-api-feed rcbsupnet/udagram-api-feed:latest
  - cd $TRAVIS_BUILD_DIR/udagram-api-user
  - docker build -t udagram-api-user .
  - docker tag udagram-api-user rcbsupnet/udagram-api-user:latest
  - cd $TRAVIS_BUILD_DIR/udagram-frontend
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend rcbsupnet/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push rcbsupnet/reverse-proxy
  - docker push rcbsupnet/udagram-api-feed
  - docker push rcbsupnet/udagram-api-user
  - docker push rcbsupnet/udagram-frontend

